config/routes.rb
Rails.application.routes.draw do

resources :reviews
devise_for :users
  
    
resources :movies
  
 
get 'home/index'
get 'help' => 'static#help'
    
get 'pages'=> 'pages#whoweare'
    
    
 # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
 resources :users 
#     do
# #     resources :movies
#  end   
    
 
#   get 'movies' => 'movies#index'

 authenticated :user do
   root 'home#index', as: 'authenticated_root'
 end
 devise_scope :user do
   root 'devise/sessions#new'
 end
resources :authentications, only: [:destroy]
 




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/movie.rb
class Movie < ApplicationRecord
 
   # has_attached_file :poster, styles: { medium:  '400x400#'}
   #  validates_attachment_content_type :poster, content_type: /\Aimage\/.*\Z/

#     belongs_to :user
    has_attached_file :poster, styles: { medium:  "400x600#"}
    validates_attachment_content_type :poster, content_type: /\Aimage\/.*\Z/

  
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :movies
  has_many :ratings
  has_many :descriptions 
  has_many :comments
  has_many :reviews, dependent: :destroy
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :movies
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
    def self.from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.provider = auth.provider
            user.uid = auth.uid
            user.password = Devise.friendly_token[0,20]
          end

    end

    def apply_omniauth(auth)
  update_attributes(provider: auth.provider, uid: auth.uid)
end






    def has_facebook_linked?
          self.provider.present? && self.uid.present?
    end
 
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
     def show
    render params[:page]
end
    def index
    @help = Help.new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!  
    
  def index
      render 
  end
    
  def index
    @movies = Movie.all
  end
    
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index]
   
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    puts movie_params
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    
    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :length, :rating, :poster)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
        def show
    render params[:page]
end
    def index
    @whoweare = Whoweare.new
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def reviews
  #   @list = Review.find(params[:user_id])
  #   @reviews = @list.reviews
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>



<div class="well" style="width: 80rem;">
    <h1> Movies </h1>

<table>
  <thead>
    <tr>
      <th> Title</th>
        
        <th> Review </th>
 
        <th> Movie length </th>
     
        <th>  Rating  </th>
     <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @movies.each do |movie| %>
   
      <tr>
        <td><%= image_tag movie.poster, class: "movie-poster"  %> </td>
          
        <td><%= movie.title %></td>
        <td><%= movie.description %></td>
        <td><%= movie.movie_length %></td>
        <td><%= movie.rating %></td>
          
        
          
          
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
    
</table>


<br>
    
<div class="btn btn-dark">
<%= link_to 'New Movie', new_movie_path %>
   
</div>
</div>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true, html: {mutlipart: true }) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= form.label :Poster %>
    <%= form.file_field :poster %>
  </div>
  <div class="field">
    <%= form.label :title %>
       <br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :Review %>
       <br>
    <%= form.text_area :description  %>
  </div>

  <div class="field">
    <%= form.label :movie_length %>
       <br>
    <%= form.text_field :movie_length  %>
  </div>

  <div class="field">
    <%= form.label :rating %>
       <br>
    <%= form.number_field :rating  %>
  </div>
<br> 


  <div class="actions" >
    <%= form.submit :class => "btn btn-secondary" %>   
  </div>

 <br>

<% end %>

app/views/movies/edit.html.erb
<div class="well" style="width: 80rem;">
<h1> Editing Movie </h1>

<%= render 'form', movie: @movie %>

    
<div class="btn btn-dark">
<%= link_to 'Show', @movie  %> |
<%= link_to 'Back', movies_path %>
</div>
    
</div>

app/views/movies/index.html.erb
<div class="container">
    

<h1><font color="white">Your Favorite Movies Reviewed</font></h1>
<br> 


<div class="row">
	  <% @movies.each do |movie| %>
	    <div class="col-sm-6 col-md-3">
	      <div class="thumbnail">
	        <%= link_to (image_tag movie.poster.url(:medium), class: 'image'), movie %>
	      </div>
	    </div>
	  <% end %>
	</div>

app/views/movies/new.html.erb
<h1> <font color="white">New Movie</font></h1>
<div class="well" style="width: 50rem;">
    

<%= render 'form', movie: @movie %>
    
    
<div class="btn btn-dark">
<%= link_to 'Back', movies_path %>
    </div>
    
    
    </div>

app/views/movies/show.html.erb
<div class="well" style="width: 80rem;">
         
<%= image_tag @movie.poster.url(:medium) %> 
    
<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Review:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Movie length:</strong>
  <%= @movie.movie_length %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @movie.rating %>
    
</p>

<div class="btn btn-dark">
<%= link_to 'Edit', edit_movie_path(@movie) %> 
    </div>
<div class="btn btn-dark">
<%= link_to 'Back', movies_path %>
    </div>
</div>