config/routes.rb
Rails.application.routes.draw do

resources :reviews
devise_for :users
  
    
resources :movies
  
 
get 'home/index'
get 'help' => 'static#help'
    
get 'pages'=> 'pages#whoweare'
    
    
 # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
 resources :users 
#     do
# #     resources :movies
#  end   
    
 
#   get 'movies' => 'movies#index'

 authenticated :user do
   root 'home#index', as: 'authenticated_root'
 end
 devise_scope :user do
   root 'devise/sessions#new'
 end
resources :authentications, only: [:destroy]
 




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/movie.rb
class Movie < ApplicationRecord
 
   # has_attached_file :poster, styles: { medium:  '400x400#'}
   #  validates_attachment_content_type :poster, content_type: /\Aimage\/.*\Z/

#     belongs_to :user
    has_attached_file :poster, styles: { medium:  "400x600#"}
    validates_attachment_content_type :poster, content_type: /\Aimage\/.*\Z/

  
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :movies
  has_many :ratings
  has_many :descriptions 
  has_many :comments
  has_many :reviews, dependent: :destroy
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :movies
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
    def self.from_omniauth(auth)
          where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.provider = auth.provider
            user.uid = auth.uid
            user.password = Devise.friendly_token[0,20]
          end

    end

    def apply_omniauth(auth)
  update_attributes(provider: auth.provider, uid: auth.uid)
end






    def has_facebook_linked?
          self.provider.present? && self.uid.present?
    end
 
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
     def show
    render params[:page]
end
    def index
    @help = Help.new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!  
    
  def index
      render 
  end
    
  def index
    @movies = Movie.all
  end
    
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
        def show
    render params[:page]
end
    def index
    @whoweare = Whoweare.new
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer ">
  <div class="footer text-center py-3">Made by: Ulysses , Lutriel , Josh:
    <a id= "link" href="https://google.com" target="_blank"> Movies@Maku.com</a>
      <a id="photoid" style="background-color:black;color:white;text-decoration:none;padding:4px 6px;font-family:-apple-system,
                BlinkMacSystemFont, &quot;San Francisco&quot;, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Roboto,
                Noto, &quot;Segoe UI&quot;, Arial, sans-serif;font-size:12px;font-weight:bold;line-height:1.2;display:inline-block;border-radius:3px"
         href="https://unsplash.com/@johnmoeses?utm_medium=referral&amp;utm_campaign=photographer-credit&amp;utm_content=creditBadge" target="_blank"
         rel="noopener noreferrer" title="Download free do whatever you want high-resolution photos from John Moeses Bauan"><span style="display:inline-block;padding:2px 3px">
          <svg xmlns="http://www.w3.org/2000/svg" style="height:12px;width:auto;position:relative;vertical-align:middle;top:-1px;fill:white" viewBox="0 0 32 32"><title>unsplash-logo</title><path d="M20.8 18.1c0 2.7-2.2 4.8-4.8 4.8s-4.8-2.1-4.8-4.8c0-2.7 2.2-4.8 4.8-4.8 2.7.1 4.8 2.2 4.8 4.8zm11.2-7.4v14.9c0 2.3-1.9 4.3-4.3 4.3h-23.4c-2.4 0-4.3-1.9-4.3-4.3v-15c0-2.3 1.9-4.3 4.3-4.3h3.7l.8-2.3c.4-1.1 1.7-2 2.9-2h8.6c1.2 0 2.5.9 2.9 2l.8 2.4h3.7c2.4 0 4.3 1.9 4.3 4.3zm-8.6 7.5c0-4.1-3.3-7.5-7.5-7.5-4.1 0-7.5 3.4-7.5 7.5s3.3 7.5 7.5 7.5c4.2-.1 7.5-3.4 7.5-7.5z"></path></svg></span><span style="display:inline-block;padding:2px 3px">John Moeses Bauan</span></a>
  </div>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse" id="head">
      <div class="container-fluid">
        <%= link_to "Maku MovieRatingApp", 'movies', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   '/movies' %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Account", 'users/sign_in' %></li>
             <li><%= link_to "WhoWeAre", '/pages' %></li>

              
         </ul>
      </nav>
    </div>
</header>
      <div id="signin">
          <% if user_signed_in? %>
              <%= link_to "Edit profile", edit_user_registration_path %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
          <% else %>
              <%= link_to "Sign up", new_user_registration_path  %> |
              <%= link_to "Login", new_user_session_path  %>
          <% end %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    <div class="container">
      <%# yield %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MakuMovieApp</title>
    <meta name="description" content="<% content_for?(:description) ? yield(:description) : "Rails Devise Roles" %>"> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
       <body>
    <header>
          <%= render 'layouts/header' %>
    </header>
     <div class="container">
          
    
         
           
    <main role="main">
        
       <%# render 'layouts/messages' %>
       <%= yield %>
    </main>
       </div>
 <footer>
    <%= render 'layouts/footer' %>
 </footer>  
      </body>
</html>

app/views/pages/whoweare.html.erb
<p class="sign"> Who </p>

<div class="well" style="width: 90rem;">
     

    
    
    
<div class="tab">
  <button class="tablinks" onmouseover="openCity(event, 'Joshua')">Joshua Meadows</button>
  <button class="tablinks" onmouseover="openCity(event, 'Lutriel')">Lutriel Dangleben</button>
  <button class="tablinks" onmouseover="openCity(event, 'Ulysses')">Ulysses Hall</button>
</div>

<div id="Joshua" class="tabcontent">
   <img class="card-img-top" src=".../100px180/?text=Image cap" alt="Card image cap">
  <h3>Joshua Meadows</h3>    
    <br>
  <p>And smug that exulting one speechless the before </p>
   <p> Less leopard excepting earthworm </p>
</div>

    
<div id="Lutriel" class="tabcontent">
    <img class="card-img-top" src=".../100px180/?text=Image cap" alt="Card image cap">
  <h3>Lutriel Dangleben</h3>
     <br>
  <h8>lutrieldangleben@hotmail.com </h8> 
   
  <p> 340-226-9655</p>
</div>

    
<div id="Ulysses" class="tabcontent">
     <img class="card-img-top" src=".../100px180/?text=Image cap" alt="Card image cap">
  <h3>Ulysses Hall</h3>
    <br>
  <p>And smug that exulting one speechless the before</p>
    <p>Less leopard excepting earthworm</p>
</div>
    
    
<div class="clearfix"></div>
</div>
    
    <script>
function openCity(evt, cityName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active","" );
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
}
</script>